### PR TITLE
Add shared schemes for tvOS, OS X and watchOS

### PR DESCRIPTION
**Pull request by tomco**
This should improve the compatibility for Carthage a lot.

### CODE REVIEW

**Comment by LoganWright** [comment]
This looks fine to me, it'll be nice to open up some Carthage support.  @gfx any thoughts here?

**Comment by gfx** [comment]
LGTM. That's great.

**Comment by LoganWright** [comment]
@tomco Any other additions necessary before this merges?

**Comment by tomco** [comment]
@LoganWright not directly. You should only bump the version and create a new tag / github release after the merge. That way Carthage can find the correct version easily.

**Comment by LoganWright** [comment]
@tomco Merged and tagged: https://github.com/gfx/Swift-PureJsonSerializer/releases/tag/1.1.0

**Pull request merged**
